{
 "title": "Ovirt Monitor",
 "description": "SysOps Ovirt Monitor from ovirt-exporter 0.9",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Boot time of the machine",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_boot_time{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "UP",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_up{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ovirt host cpu current idle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_cpu_current_idle_percent{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Number of CPU cores assigned",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_cpu_cores{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ovirt host cpu current user",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_cpu_current_user_percent{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ovirt host cpu current system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_cpu_current_system_percent{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ovirt host cpu sockets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_cpu_sockets{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ovirt host cpu load 5m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_cpu_load_avg_5m_percent{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ovirt host cpu threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_cpu_threads{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ovirt host cpu speed hertz",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_cpu_speed_hertz{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ovirt host ksm cpu  current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_ksm_cpu_current_percent{cluster=\"Default\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ovirt host cpu hugepages free",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_hugepages_1048576_free{cluster=\"Default\"}",
       "legendFormat": "{{name}} hugepages_1048576"
      },
      {
       "expr": "ovirt_host_hugepages_2048_free{cluster=\"Default\"}",
       "legendFormat": "{{name}} hugepages_2048"
      }
     ]
    },
    {
     "title": "ovirt host memory  swap free",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_swap_free_bytes{cluster=\"Default\"}",
       "legendFormat": "{{name}} free"
      },
      {
       "expr": "ovirt_host_swap_total_bytes{cluster=\"Default\"}",
       "legendFormat": "{{name}} total"
      }
     ]
    },
    {
     "title": "ovirt host memory  current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_memory_free_bytes{cluster=\"Default\"}",
       "legendFormat": "{{name}} free"
      },
      {
       "expr": "ovirt_host_memory_shared_bytes{cluster=\"Default\"}",
       "legendFormat": "{{name}} shared"
      },
      {
       "expr": "ovirt_host_memory_total_bytes{cluster=\"Default\"}",
       "legendFormat": "{{name}} total"
      },
      {
       "expr": "ovirt_host_memory_used_bytes{cluster=\"Default\"}",
       "legendFormat": "{{name}} used"
      }
     ]
    },
    {
     "title": "ovirt host network received bits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_network_data_current_rx_bps_bits_per_second{cluster=\"Default\"}",
       "legendFormat": "{{name}}  {{nic}} {{mac}} receive"
      }
     ]
    },
    {
     "title": "ovirt host memory  swap used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_swap_used_bytes{cluster=\"Default\"}",
       "legendFormat": "{{name}} used"
      }
     ]
    },
    {
     "title": "ovirt host network received Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_network_data_current_rx_bytes_per_second{cluster=\"Default\"}",
       "legendFormat": "{{name}}  {{nic}} {{mac}} receive"
      }
     ]
    },
    {
     "title": "ovirt host network transmit bits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_network_data_current_tx_bps_bits_per_second{cluster=\"Default\"}",
       "legendFormat": "{{name}}  {{nic}} {{mac}} receive"
      }
     ]
    },
    {
     "title": "ovirt host network received Bytes total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_network_data_rx_bytes_total{cluster=\"Default\"}",
       "legendFormat": "{{name}}  {{nic}} {{mac}} receive"
      }
     ]
    },
    {
     "title": "ovirt host network transmit Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_network_data_current_tx_bytes_per_second{cluster=\"Default\"}",
       "legendFormat": "{{name}}  {{nic}} {{mac}} receive"
      }
     ]
    },
    {
     "title": "ovirt host network received errors total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_network_errors_rx_total{cluster=\"Default\"}",
       "legendFormat": "{{name}}  {{nic}} {{mac}} receive"
      }
     ]
    },
    {
     "title": "ovirt host network transmitted Bytes total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_network_data_tx_bytes_total{cluster=\"Default\"}",
       "legendFormat": "{{name}}  {{nic}} {{mac}} receive"
      }
     ]
    },
    {
     "title": "ovirt host network transmitted errors total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ovirt_host_network_errors_tx_total{cluster=\"Default\"}",
       "legendFormat": "{{name}}  {{nic}} {{mac}} receive"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available space in bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ovirt_storage_available_bytes{job=\"ovirt-sysops\"}",
       "legendFormat": "{{name}}  {{path}} {{type}}"
      }
     ]
    },
    {
     "title": "Committed space in bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ovirt_storage_committed_bytes{job=\"ovirt-sysops\"}",
       "legendFormat": "{{name}}  {{path}} {{type}}"
      }
     ]
    },
    {
     "title": "Storage domain is master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ovirt_storage_master{job=\"ovirt-sysops\"}",
       "legendFormat": "{{name}}  {{path}} {{type}}"
      }
     ]
    },
    {
     "title": "Used space in bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ovirt_storage_used_bytes{job=\"ovirt-sysops\"}",
       "legendFormat": "{{name}}  {{path}} {{type}}"
      }
     ]
    },
    {
     "title": "Status of storage domain",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ovirt_storage_up{job=\"ovirt-sysops\"}",
       "legendFormat": "{{name}}  {{path}} {{type}}"
      }
     ]
    }
   ]
  },
  { "title": "vm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": " Number of CPU cores assigned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_cpu_cores{job=\"ovirt-sysops\"}",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  },
  {
   "title": "Number of sockets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_cpu_sockets{job=\"ovirt-sysops\"}",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  },
  {
   "title": "vm CPU overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_cpu_current_hypervisor_percent{job=\"ovirt-sysops\"}",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  },
  {
   "title": "vm cpu guest_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_cpu_current_guest_percent{job=\"ovirt-sysops\"}",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  },
  {
   "title": "vm Total CPU used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_cpu_current_total_percent{job=\"ovirt-sysops\"} / (ovirt_vm_cpu_cores{job=\"ovirt-sysops\"} * ovirt_vm_cpu_sockets{job=\"ovirt-sysops\"})",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  },
  {
   "title": "vm Number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_cpu_threads{job=\"ovirt-sysops\"}",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  },
  {
   "title": "vm Actual size of the disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_disk_actual_size_bytes{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  {{storage_domain}}  {{disk _name}}"
    }
   ]
  },
  {
   "title": "vm Provisioned size of the disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_disk_provisioned_size_bytes{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  {{storage_domain}}  {{disk _name}}"
    }
   ]
  },
  {
   "title": "vm Total size of the disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_disk_total_size_bytes{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  {{storage_domain}}  {{disk _name}}"
    }
   ]
  },
  {
   "title": " Elapsed VM runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ovirt_vm_elapsed_time_seconds_total{job=\"ovirt-sysops\",cluster=\"Default\"}[1m])",
     "legendFormat": "{{host}}  {{name}}  {{storage_domain}}  {{disk _name}}"
    }
   ]
  },
  {
   "title": " Health status of the disks",
   "type": "graph",
   "description": " Health status of the disks attatched to the VM (1 if one or more disk is in illegal state)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_illegal_images{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  "
    }
   ]
  },
  {
   "title": "Memory buffered (agent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_memory_buffered_bytes{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  "
    }
   ]
  },
  {
   "title": "Memory cached (agent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_memory_cached_bytes{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  "
    }
   ]
  },
  {
   "title": "Memory free (agent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_memory_free_bytes{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  free"
    },
    {
     "expr": "ovirt_vm_memory_installed_bytes{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  installed"
    }
   ]
  },
  {
   "title": "Migration Progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_migration_progress_percent{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  "
    }
   ]
  },
  {
   "title": "Memory used (agent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_memory_used_bytes{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  used"
    },
    {
     "expr": "ovirt_vm_memory_installed_bytes{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  installed"
    }
   ]
  },
  {
   "title": "Total network used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_network_current_total_percent{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  "
    }
   ]
  },
  {
   "title": "Receive & Transmit data rate （bit）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_network_data_current_rx_bps_bits_per_second{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  receive"
    },
    {
     "expr": "ovirt_vm_network_data_current_x_bps_bits_per_second{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  transmit"
    }
   ]
  },
  {
   "title": "Receive & Transmit Total  data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_network_data_rx_bytes_total{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  received"
    },
    {
     "expr": "ovirt_vm_network_data_x_bytes_total{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  Transmit"
    }
   ]
  },
  {
   "title": "Receive & Transmit data rate （byte）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_network_data_current_rx_bytes_per_second{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  receive"
    },
    {
     "expr": "ovirt_vm_network_data_current_x_bytes_per_second{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  transmit"
    }
   ]
  },
  {
   "title": "Age of the oldest snapshot ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_snapshot_max_age_seconds{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  },
  {
   "title": "Receive & Transmit data Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_network_errors_rx_total{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  receive"
    },
    {
     "expr": "ovirt_vm_network_errors_tx_total{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}}  transmit"
    }
   ]
  },
  {
   "title": "Age of the newest snapshot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_snapshot_min_age_seconds{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  },
  {
   "title": "Number of snapshots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_snapshots{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  },
  {
   "title": "VM is running (1) or not (0)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovirt_vm_up{job=\"ovirt-sysops\",cluster=\"Default\"}",
     "legendFormat": "{{host}}  {{name}} "
    }
   ]
  }
 ]
}